Added more tests for app.
k0sm0naft/java-online-book-store pull request #15
Opened 2024-05-15 12:18 UTC by k0sm0naft

![image](https://github.com/k0sm0naft/java-online-book-store/assets/113580621/0aec22f3-eadf-49dc-a5f9-eb6ae8f0ab45)

2024-05-17 07:51 UTC, karma-o commented
**89%** of line coverage throughout the whole project, very cool 🔥🚒

2024-05-17 09:03 UTC, karma-o requested changes

2024-05-17 09:03 UTC, karma-o commented on src/main/java/ua/bookstore/online/repository/order/item/OrderItemRepository.java
> +    Optional<OrderItem> findByIdAndOrder_IdAndOrder_User(Long id, Long orderId, User user);
these method names are very confusing

2024-05-17 09:03 UTC, karma-o commented on src/main/java/ua/bookstore/online/service/impl/ShoppingCartServiceImpl.java
> +                () -> new EntityNotFoundException("Can't update item in an empty cart"));
cart does not exist at all here, it is not just empty, which can be misleading

2024-05-17 09:03 UTC, karma-o commented on src/main/java/ua/bookstore/online/service/impl/ShoppingCartServiceImpl.java
> +                () -> new EntityNotFoundException("Can't update item in an empty cart"));
btw, I remember we had a conversation about creating a cart during user registration vs on the fly, just curious, have you asked Bohdan or anybody else? and how does it work now?

2024-05-17 09:03 UTC, karma-o commented on src/main/java/ua/bookstore/online/service/impl/ShoppingCartServiceImpl.java
> +                () -> new EntityNotFoundException("Can't remove item from empty cart"));
same message problem here

2024-05-17 09:03 UTC, karma-o commented on src/test/java/ua/bookstore/online/utils/ConstantAndMethod.java
>  public class ConstantAndMethod {
I think it is safe to say that this class mostly provides some test data, so
```suggestion
public class DataUtils {
```
and let's add private constructor for it, and maybe even throw some exception there, on attempt to call it

2024-05-17 09:03 UTC, karma-o commented on src/test/java/ua/bookstore/online/service/impl/BookServiceImplTest.java
>      void delete_ExistingBook_SuccessfullyDeleted() {
I do not see those fully as additions here, I assume we had part of the tests written in some of the previous PRs, were they reviewed properly? Because I do not remember that we had any tests-related task before that one

2024-05-17 09:03 UTC, karma-o commented on src/test/java/ua/bookstore/online/service/impl/BookServiceImplTest.java
> -        verify(bookRepository).deleteById(ID_1);
why did you remove the verification that repo methods were called?
Same for other methods

2024-05-17 09:03 UTC, karma-o commented on src/test/java/ua/bookstore/online/service/impl/CartItemServiceImplTest.java
> +    void changeQuantity_UpdatesNonExistingCartItemQuantity_ReturnsQuantityDto() {
it actually expects an exception to be thrown

2024-05-17 09:03 UTC, karma-o commented on src/test/java/ua/bookstore/online/service/impl/CartItemServiceImplTest.java
> +        assertDoesNotThrow(() -> cartItemService.remove(cartItemId, shoppingCart));
just an assertion that it does not throw anything does not look very useful, can we maybe return something from this `remove()` method that we can assert? and maybe check some similar places if you have any

2024-05-17 09:03 UTC, karma-o commented on src/test/java/ua/bookstore/online/service/impl/CategoryServiceImplTest.java
>      void deleteById_ExistingCategory_Ok() {
again part of the tests are already in the main branch, were they reviewed?

2024-05-17 09:03 UTC, karma-o commented on src/test/java/ua/bookstore/online/service/impl/OrderItemServiceImplTest.java
> +                () -> orderItemService.findAllByOrder(NON_EXISTING_ID, user, pageable));
Also wanted to recommend, not for this task but just for the future: there is a useful class for other asserting stuff named `Assertions` (not sure if you have it or you need a junit jupiter or some other junit dependency for it) and it has a method `assertThat(actual)` which is very flexible and works by the builder pattern, with more specific error messages, for example:
```java
assertThat(someList).hasSize(1);

assertThatThrownBy(SomeEx.class, () -> service.method(var))
    .hasMessage("message");

assertThat(list)
    .usingRecursiveComparision()
    .ignringFields(fields)
    .ignoringCollectionsOrder()
    .isEqualTo(expected);
```

2024-05-17 09:03 UTC, karma-o commented on src/test/java/ua/bookstore/online/service/impl/ShoppingCartServiceImplTest.java
> +    void updateCartItem_UpdateItemInNonExistingCart_ReturnsQuantityDto() {
another name incorrespondance to the body, please double-check other classes & methods as well

2024-05-17 09:03 UTC, karma-o commented on src/test/java/ua/bookstore/online/service/impl/ShoppingCartServiceImplTest.java
> +    @DisplayName("Update cart item in non-existing shopping cart")
I'd also probably add what we expect as a result of those actions to the display name

2024-05-18 07:52 UTC, k0sm0naft commented on src/main/java/ua/bookstore/online/service/impl/ShoppingCartServiceImpl.java
> +                () -> new EntityNotFoundException("Can't update item in an empty cart"));
I didn't ask Bohdan (or had already forgotten about it). I talked to Andriy, and we decided to leave it that way. Furthermore, I think it's not important for this project.

2024-05-18 08:08 UTC, k0sm0naft commented on src/test/java/ua/bookstore/online/service/impl/BookServiceImplTest.java
>      void delete_ExistingBook_SuccessfullyDeleted() {
Yes, previous RP contains part of tests. It was reviewed and approved. But was advice about verification of methods that I apply in this RP.

2024-05-18 08:13 UTC, k0sm0naft commented on src/test/java/ua/bookstore/online/service/impl/BookServiceImplTest.java
> -        verify(bookRepository).deleteById(ID_1);
As it was explained to me, if I mock a method, the call to this class is verified, and it remains to check whether there were any unplanned calls by `verifyNoMoreInteractions()`.

2024-05-18 08:14 UTC, k0sm0naft commented on src/test/java/ua/bookstore/online/service/impl/BookServiceImplTest.java
> -        verify(bookRepository).deleteById(ID_1);
And cod become cleaner and easier to read.

2024-05-18 10:56 UTC, k0sm0naft commented on src/test/java/ua/bookstore/online/service/impl/CategoryServiceImplTest.java
>      void deleteById_ExistingCategory_Ok() {
Yep.
[Massage]( https://github.com/k0sm0naft/java-online-book-store/pull/14#discussion_r1601287382)

2024-05-18 10:59 UTC, k0sm0naft commented on src/test/java/ua/bookstore/online/service/impl/OrderItemServiceImplTest.java
> +                () -> orderItemService.findAllByOrder(NON_EXISTING_ID, user, pageable));
It's useful information, thanks.

2024-05-20 11:57 UTC, k0sm0naft commented on src/main/java/ua/bookstore/online/repository/order/item/OrderItemRepository.java
> +    Optional<OrderItem> findByIdAndOrder_IdAndOrder_User(Long id, Long orderId, User user);
Discussed with QnA. I leave EntityGraph.

2024-05-22 13:01 UTC, andrii-hoienko approved these changes
Very nice

2024-05-22 13:05 UTC, merged