Added Pagination, Sorting, and Swagger to the BookController.
k0sm0naft/java-online-book-store pull request #6
Opened 2024-04-10 16:03 UTC by k0sm0naft

2024-04-10 19:20 UTC, ReamFOX approved these changes
LGTM

2024-04-11 15:31 UTC, andrii-hoienko requested changes
I think more changes should be in this pr, there is no changes regarding Pagination and Sorting

2024-04-12 06:50 UTC, karma-o requested changes
Looks good so far, left some comments, please take a look

2024-04-12 06:50 UTC, karma-o commented on src/main/java/ua/bookstore/online/controller/BookController.java
>              @RequestBody @Valid CreateBookRequestDto bookDto) {
Let's add request body documentation to swagger, including a description of it's fields, types etc.

2024-04-12 06:50 UTC, karma-o commented on src/main/java/ua/bookstore/online/controller/BookController.java
> +    public List<BookDto> getAll(Pageable pageable) {
seems strange that documentation says that we are returning a page of books, but in fact, it is a list

2024-04-12 06:50 UTC, karma-o commented on src/main/java/ua/bookstore/online/controller/BookController.java
> +    public List<BookDto> searchBooks(Pageable pageable, BookSearchParameters bookSearchParameters) {
same here, let's return a page of books

2024-04-12 06:50 UTC, karma-o commented on src/main/java/ua/bookstore/online/service/BookServiceImpl.java
> +        if (bookRepository.existsById(id)) {
I'd flip that `if`, to follow the fail early pattern

2024-04-12 12:18 UTC, k0sm0naft commented on src/main/java/ua/bookstore/online/service/BookServiceImpl.java
> +        if (bookRepository.existsById(id)) {
But I think my it is better than `!` at the beginning.
```suggestion
        if (!bookRepository.existsById(id)) {
```
Or should I write it like :
```suggestion
        if (bookRepository.existsById(id) == false) {
```

2024-04-12 14:31 UTC, andrii-hoienko approved these changes
Good job!

2024-04-12 14:32 UTC, merged